import React from 'react';

import './globals.css';

import { pretendard } from '@/utils/fonts';

import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${pretendard.variable} font-pretendard`}>{children}</body>
		</html>
	);
}
